Adherence to best practices
MetaStudioLand/protocol-contracts pull request #39
Opened 2022-07-26 14:27 UTC by Nassimov

2022-07-26 21:02 UTC, mvanmeerbeck requested changes

2022-07-27 10:11 UTC, Nassimov commented on src/contracts/metatx/ERC2771ContextUpgradeable.sol
> +        return super._msgData();
> ?????? why did u change that ?

Because it's never called by MetaStudioToken and this is why there is 50% in branch in ERC2771 coverage result.

2022-07-28 08:42 UTC, mvanmeerbeck requested changes

2022-07-28 08:42 UTC, mvanmeerbeck commented on src/contracts/metatx/ERC2771ContextUpgradeable.sol
> +        return super._msgData();
If it's not used at all, ask qsp if it's safe to remove the function _msgData

I think it is
https://eips.ethereum.org/EIPS/eip-2771

2022-07-28 08:52 UTC, Nassimov commented on src/contracts/metatx/ERC2771ContextUpgradeable.sol
> +        return super._msgData();
I tried to remove it  but it throws an error , it seems to be a required method

2022-07-29 15:04 UTC, merged